import {
  Button,
  Card,
  Container,
  Divider,
  Grid,
  Group,
  Stack,
  Text,
  Title,
  useMantineTheme,
} from "@mantine/core";
import { useClipboard } from "@mantine/hooks";
import { IconCheck, IconCopy } from "@tabler/icons-react";
import { type NextPage } from "next";
import Head from "next/head";

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Title order={1}>Unser Angebot</Title>
        <Title order={3} weight={400}>
          Wir sind Teil vom Commandmc.eu Netzwerk
        </Title>
        <Stack mt="sm">
          <ServerCard
            title="Commandmc.eu"
            description="Einfach Bedwars, aber besser. Wir haben die besten Aspekte der grossen Server genommen und zusammengesetzt. Zudem ist natürlich alles in der 1.19.3, aber mit 1.8 PvP. Es gibt viele Extraitems und Möglichkeiten das Spiel ganz neu zu erleben. Dank unserem einzigartigen Maperstellungssystem hast du nun die Möglichkeit deine eigenen Maps zu erstellen und mit oder gegen Freunde zu spielen."
            address="commandmc.eu"
            version="1.19.3"
            players="2 bis 12"
            duration="5 bis 40 Minuten"
          />

          <ServerCard
            title="Spightwars"
            description="Eine Mischung aus Survival und Bedwars. Du spawnst auf einer Survivalmap bei deinem Bett und farmst in dieser deine Ausrüstung um dann bei epischen Kämpfen die Betten der anderen zu zerstören. Neben den normalen Survival-Aspekten gibt es noch ein paar Extras. Beispielseise kannst du durch Kupfer Netherite bekommen oder Blätter droppen zu einer bestimmten Wahrscheinlichkeit Goldäpfel."
            address="sw.commandmc.eu"
            version="1.19.2"
            players="2 bis 30"
            duration="20 bis 60 Minuten"
          />
        </Stack>
      </Container>
    </>
  );
};

export default Page;

interface ServerCardProps {
  title: string;
  description: string;
  address: string;
  version: string;
  players: string;
  duration: string;
}

const ServerCard = ({
  title,
  description,
  address,
  version,
  players,
  duration,
}: ServerCardProps) => {
  return (
    <Card>
      <Group position="apart">
        <Title order={4}>{title}</Title>
        <CopyButton value={description} />
      </Group>
      <Text>{description}</Text>
      <Divider my="sm" />
      <Grid>
        <Grid.Col span={12} xs={6} sm={4} md={3}>
          <Text weight={500}>Serveradresse</Text>
          <Title order={3}>{address}</Title>
        </Grid.Col>
        <Grid.Col span={12} xs={6} sm={4} md={3}>
          <Text weight={500}>Version</Text>
          <Title order={3}>{version}</Title>
        </Grid.Col>
        <Grid.Col span={12} xs={6} sm={4} md={3}>
          <Text weight={500}>Spieler</Text>
          <Title order={3}>{players}</Title>
        </Grid.Col>
        <Grid.Col span={12} xs={6} sm={4} md={3}>
          <Text weight={500}>Dauer</Text>
          <Title order={3}>{duration}</Title>
        </Grid.Col>
      </Grid>
    </Card>
  );
};

interface CopyButtonProps {
  value: string;
}

const CopyButton = ({ value }: CopyButtonProps) => {
  const { copy, copied } = useClipboard({ timeout: 1000 });
  const { colors } = useMantineTheme();

  if (copied) {
    return (
      <Button
        size="xs"
        variant="default"
        leftIcon={<IconCheck color={colors.teal[5]} size={16} />}
      >
        Serveradresse kopiert
      </Button>
    );
  }

  return (
    <Button
      variant="default"
      size="xs"
      leftIcon={<IconCopy size={16} />}
      onClick={() => copy(value)}
    >
      Serveradresse kopieren
    </Button>
  );
};
