import {
  Card,
  Container,
  Group,
  Stack,
  Title,
  Text,
  ActionIcon,
} from "@mantine/core";
import { IconExternalLink } from "@tabler/icons-react";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import type { Player } from "../server/api/routers/player";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const players = api.player.all.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Title order={1}>Übersicht der Spieler</Title>

        <Stack mt="sm" spacing="sm">
          {players.data?.map((player) =>
            player.id ? (
              <Card key={player.id} shadow="sm">
                <Group position="apart">
                  <Group>
                    <Image
                      height={32}
                      width={32}
                      src={`https://mc-heads.net/avatar/${player.name}/100/nohelm.png`}
                      alt={`Player head of ${player.name}`}
                    />
                    <Title order={3} color={getRankColor(player)}>
                      {player.name}
                    </Title>
                  </Group>
                  <ActionIcon
                    component={Link}
                    href={`/players/${player.name.toLowerCase()}`}
                  >
                    <IconExternalLink size={20} />
                  </ActionIcon>
                </Group>
              </Card>
            ) : null
          )}
        </Stack>
      </Container>
    </>
  );
};

export default Home;

const getRankColor = (player: Player) => {
  return player.display.rank.split('"color":"')[1]?.split('"')[0];
};
